### PR TITLE
Textinput and flipswitch: Use .nodeName and .toLowerCase()

### LINKED ISSUE #7959: Code for comparing .tagName misses .toLowerCase() or .toUpperCase() for XHTML
Hi,

after issue #7849 was closed, I found another bug that manifests when jQuery Mobile 1.4.5 is included in an XHTML page served with a Content-Type of "application/xhtml+xml".

The problem is that when using .tagName of an element, in HTML it will be returned in upper case (e.g. "INPUT") while XHTML as XML is case-sensitive and will return the tag name in lower-case ("input"). jQM has a few lines where the the tag name is compared in upper-case - this will fail in XHTML documents.

I found the following lines in https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.js where the problem occurs:
Line 8336
```javascript
isTextarea = this.element[ 0 ].tagName === "TEXTAREA",
```
Line 9215
```javascript
type: this.element.get( 0 ).tagName
```
Line 9291
```javascript
type = element.get( 0 ).tagName,
```

The code should be changed to either call .tagName.toUpperCase(), or to call .tagName.toLowerCase() and then do a lower-case comparison.

Thanks!

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Fixes gh-7959

### CODE REVIEW

File: js/widgets/forms/flipswitch.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ $.widget( "mobile.flipswitch", $.extend({
 					flipswitch: this.element.parent(),
 					on: this.element.find( ".ui-flipswitch-on" ).eq( 0 ),
 					off: this.element.find( ".ui-flipswitch-off" ).eq(0),
-					type: this.element.get( 0 ).tagName
+					type: this.element.get( 0 ).nodeName.toLowerCase()
```
Comment (arschmitz) [inline js/widgets/forms/flipswitch.js]: we dont as a rule use `.get( 0 )` use `this.element[ 0 ]`

Comment (arschmitz) [inline js/widgets/forms/flipswitch.js]: This should be moved out of the conditional it needs to run either way. Just do `this.type = this.element.get( 0 ).nodeName.toLowerCase()`  as the first thing in create and remove from `enhance`.

**Comment by arschmitz** [comment]
textinput and flipswitch should be in separate commits aside from that :+1:
